version: '3.8'

services:
  web-server:
    build:
      context: .
      dockerfile: docker/web-server/dockerFile
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html

  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=${CLOUDFLARE_ZONE}
      - SUBDOMAIN=${CLOUDFLARE_SUBDOMAIN}
      - PROXIED=false
