version: '3.8'

services:
  web-server:
    build:
      context: .
      dockerfile: docker/web-server/dockerFile
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html

  ddns-client:
    build:
      context: ./docker/ddns-client
      dockerfile: dockerFile
    env_file:
      - .env

