FROM alpine:latest

# Instalar curl
RUN apk --no-cache add curl bash

# Copiar el script al contenedor y darle permisos de ejecución
COPY ddns_updater.sh /ddns_updater.sh
RUN chmod +x /ddns_updater.sh

# Establecer el script como punto de entrada
ENTRYPOINT ["/ddns_updater.sh"]
